// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Keep Prisma CLI on a local SQLite file.
    // Turso is used by the runtime adapter in src/lib/prisma.ts.
    url:
      process.env["LOCAL_DATABASE_URL"] ||
      process.env["DATABASE_URL"] ||
      "file:./prisma/dev.db",
  },
});
